---
- name: Ubuntu 20.04 focal docker installation from .deb
  hosts: ubuntu
  # --ask-become-pass at runtime

  vars:
    - server_user: user
    - focal_url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64
    - debfiles:
        - docker-ce-cli_20.10.13~3-0~ubuntu-focal_amd64.deb
        - containerd.io_1.4.13-1_amd64.deb
        - docker-ce_20.10.13~3-0~ubuntu-focal_amd64.deb
        - docker-compose-plugin_2.3.3~ubuntu-focal_amd64.deb

  tasks:
    - name: Uninstall docker snap
      community.general.snap:
        name: docker
        state: absent
      become: true

    - name: Make docker_installation directory
      ansible.builtin.file:
        path: "/home/{{ server_user }}/docker_installation"
        state: directory

    - name: Download docker .deb files for Ubuntu 20.04 focal
      ansible.buildin.get_url:
        url: "{{ item }}"
        dest: "/home/{{ server_user }}/docker_installation/"
      loop:
        - "{{ focal_url }}/{{ debfiles[0] }}"
        - "{{ focal_url }}/{{ debfiles[1] }}"
        - "{{ focal_url }}/{{ debfiles[2] }}"
        - "{{ focal_url }}/{{ debfiles[3] }}"

    - name: Install docker deb packages
      ansible.builtin.apt:
        deb: "/home/{{ server_user }}/docker_installation/{{ item }}"
      loop:
        - "{{ debfiles[0] }}"
        - "{{ debfiles[1] }}"
        - "{{ debfiles[2] }}"
        - "{{ debfiles[3] }}"
      become: true

    - name: Add {{ server_user }} to docker group
      ansible.builtin.user:
        name: "{{ server_user }}"
        groups: docker
        append: yes
      become: true

    - name: Add docker-compose path to .profile
      ansible.builtin.lineinfile:
        path: "/home/{{ server_user }}/.profile"
        line: export PATH="/usr/libexec/docker/cli-plugins:$PATH"

    - name: Check if docker services are running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - containerd
        - docker

    - name: install python package manager
      apt:
        name: python3-pip

    - name: install python sdk
      become_user: "{{ lookup('env','USER') }}"
      pip:
        name:
          - docker
          - docker-compose
