---

- name: Initialise a fresh Ubuntu installation
  hosts: nextcloud
  vars:
    - lxc_user: ubuntu

  tasks:

    - name: System Upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true

    - name: Install my favorite packages if not already installed.
      ansible.builtin.apt:
        name:
          # - qemu-guest-agent
          - git
          - vim
          - tmux
          - zsh
          - zsh-syntax-highlighting
          - sshfs
          - python3-pip
          - rsync
          - htop
          - wget
          - curl
          - nnn
          - lynx
          # - remind
          - fzf
          - jq
        state: present
      become: true

    - name: Create bin directory on user home
      ansible.builtin.file:
        path: /home/{{ lxc_user }}/bin
        mode: 0744
        state: directory
        owner: 1000

    - name: Create git directory on user home
      ansible.builtin.file:
        path: /home/{{ lxc_user }}/git
        mode: 0744
        state: directory
        owner: 1000

    - name: Clone tmux-themepack git repo
      ansible.builtin.git:
        repo: 'https://github.com/jimeh/tmux-themepack.git'
        dest: '/home/{{ lxc_user }}/git/tmux-themepack'
        version: master
        clone: true
        update: true

    - name: Copy over some useful dot files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/
        mode: 0644
        owner: 1000
      when: 'ansible_hostname not in "zen"'
      loop:
        - ./files/.tmux.conf
        - ./files/.zshrc

    - name: Install useful Python modules
      ansible.builtin.pip:
        name:
          - pip
          - wheel
          - setuptools
