---

- name: Initialise a fresh Ubuntu installation
  hosts: xubuntu2204

  tasks:

    - name: System Upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true

    - name: Install my favorite packages if not already installed.
      ansible.builtin.apt:
        name:
          # - qemu-guest-agent
          - git
          - vim
          - tmux
          - zsh
          - zsh-syntax-highlighting
          - sshfs
          - python3-pip
          - rsync
          - htop
          - wget
          - curl
          - nnn
          - lynx
          # - remind
          - fzf
          - jq
        state: present
      become: true

    - name: Create bin directory on user home
      ansible.builtin.file:
        path: /home/alexk7110/bin
        mode: 0744
        state: directory

    - name: Create git directory on user home
      ansible.builtin.file:
        path: /home/alexk7110/git
        mode: 0744
        state: directory

    - name: Clone usefull git repos in ~/git
      ansible.builtin.git:
        repo: 'https://github.com/jimeh/tmux-themepack.git'
        dest: '/home/{{ ansible_user_id }}/git/tmux-themepack'
        version: master
        clone: true
        update: true

    - name: Copy over some useful dot files
      ansible.builtin.copy:
        src: ~/.tmux.conf
        dest: ~/
        mode: 0644

    - name: Install useful Python modules
      ansible.builtin.pip:
        name:
          - pip
          - wheel
          - setuptools
